name: Develop

on:
  push:
    branches: '**'

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: pnpm i
        shell: bash
        working-directory: ./backend-nest

      - run: pnpm test:e2e
        shell: bash
        working-directory: ./backend-nest
