name: Develop

on:
  push:
    branches: "**"

jobs:
  backend-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: "*/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm i
        shell: bash
        working-directory: ./backend-nest

      - name: Lint
        run: pnpm lint
        shell: bash
        working-directory: ./backend-nest

      - name: Build
        run: pnpm build
        shell: bash
        working-directory: ./backend-nest

  backend-e2e:
    needs:
      - backend-static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
          cache-dependency-path: "*/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm i
        shell: bash
        working-directory: ./backend-nest

      - run: pnpm test:e2e
        shell: bash
        working-directory: ./backend-nest
