export const CHAT_ROOM_REPOSITORY_PROVIDER = Symbol('CHAT_ROOM_REPOSITORY')

export const CHAT_ROOM_MESSAGE_REPOSITORY_PROVIDER = Symbol(
  'CHAT_ROOM_MESSAGE_REPOSITORY'
)

export const CHAT_ROOM_MEMBER_REPOSITORY_PROVIDER = Symbol(
  'CHAT_ROOM_MEMBER_REPOSITORY_PROVIDER'
)
